### ISSUE TITLE
Incorrect values

### ISSUE THREAD

**Issue by rodinalex** [jlapeyre/FunctionZeros.jl#10]
There appear to be some issues with certain inputs:
```besselj_zero(6, 1)``` returns 36.4 instead of 9.94
```besselj_zero(7, 2)``` returns a negative value (-0.0474)

Smaller nu's seem to work better.

**Comment by jlapeyre** [comment]
Thanks. The initial approximation in these cases is in the wrong basin, ie surrounding the wrong zero. We need a better approximation in these cases.

**Comment by jlapeyre** [comment]
The two examples in the original post in this issue now work. Roots are still incorrect for much higher `nu` together with low root number; for example `besselj_zero(60, 1)` is incorrect, but `besselj_zero(60, 2)` is correct.
