### ISSUE TITLE
besselj_zero(-60, 6) fails

### ISSUE THREAD

**Issue by reesepathak** [jlapeyre/FunctionZeros.jl#2]
executing `besselj_zero(-60, 6)` fails and produces error `Roots.ConvergenceFailed("Stopped at: xn = -731.6759022053092")`. 

is there any workaround?

**Comment by jlapeyre** [comment]
This should be fixed by addressing issue #12.

**Comment by jlapeyre** [comment]
Fixed in v0.2.3.  `besselj_zero(-60, 6)` converges to the correct result.
