### ISSUE TITLE
Register v0.2.0

### ISSUE THREAD

**Issue by sethaxen** [jlapeyre/FunctionZeros.jl#6]
It looks like v0.2.0 failed to register because the v0.2.0 tag already existed. v0.1.1 is the [current version](https://github.com/JuliaRegistries/General/blob/master/F/FunctionZeros/Versions.toml) in the registry.

Bumping to v0.2.1 and registering would work, else the v0.2.0 tag would need to be deleted.

**Comment by jlapeyre** [comment]
I just tried bumping to v0.2.1 and releasing using the web interface. If this fails, we can reopen this issue.

**Comment by jtravs** [comment]
Are you sure this worked? The registered version still seems to be v0.1.1?

**Comment by jtravs** [comment]
@jlapeyre it seems like the current version is still 0.1.1: https://github.com/JuliaRegistries/General/blob/master/F/FunctionZeros/Versions.toml
This is preventing us from using this package due to other dependencies conflicting.

**Comment by jlapeyre** [comment]
@jtravs Thanks I'll try to fix this.

**Comment by jlapeyre** [comment]
@jtravs @sethaxen  The new version has not been registered. I have not received any replies in the past two weeks, I assume I won't. I have some time this evening to work on registering a new version. I might need to get someone to close the existing issue in the general registry https://github.com/JuliaRegistries/General/pull/44375. If you have any ideas on how to register a new version, please let me know.

**Comment by jlapeyre** [comment]
I deleted all v0.2.x tags remotely and locally. I reset the version in `Project.toml` to v0.2.0. I made another request to register a version. This might work.
